version: '3.8'

services:
  my-flask-app:
    build: .
    ports:
      - "4000:5000"
    volumes:
      - .:/app
    environment:
      - NAME=World

  typst:
    image: ghcr.io/typst/typst:latest
    volumes:
      - typst-data:/data

volumes:
  typst-data:
